apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-11-03T11:16:45Z"
  generation: 1
  labels:
    run: docker-react
  name: docker-react
  namespace: default
  resourceVersion: "28620"
  selfLink: /apis/apps/v1/namespaces/default/deployments/docker-react
  uid: 24fa756e-2c17-413d-b523-9ea6d53187ac
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: docker-react
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: docker-react
    spec:
      containers:
      - image: saifmaruf/docker-react
        imagePullPolicy: Always
        name: docker-react
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2019-11-03T11:16:52Z"
    lastUpdateTime: "2019-11-03T11:16:52Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-11-03T11:16:45Z"
    lastUpdateTime: "2019-11-03T11:16:52Z"
    message: ReplicaSet "docker-react-6d4646fdd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
