apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-11-03T11:17:03Z"
  labels:
    run: docker-react
  name: docker-react
  namespace: default
  resourceVersion: "28640"
  selfLink: /api/v1/namespaces/default/services/docker-react
  uid: 64042207-8b8b-4864-8503-43f101abb740
spec:
  clusterIP: 10.100.4.17
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30199
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: docker-react
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
